<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\Container0lai10o\srcDevDebugProjectContainer::class, false)) {
    require __DIR__.'/Container0lai10o/srcDevDebugProjectContainer.php';
}

if (!class_exists(srcDevDebugProjectContainer::class, false)) {
    class_alias(\Container0lai10o\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container0lai10o\srcDevDebugProjectContainer();
