<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\AppCreateTournamentCommand' shared autowired service.

require_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
require_once $this->targetDirs[3].'/src/Command/AppCreateTournamentCommand.php';

$this->services['App\Command\AppCreateTournamentCommand'] = $instance = new \App\Command\AppCreateTournamentCommand(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});

$instance->setName('app:createTournament');

return $instance;
