<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Homepage' shared autowired service.

require_once $this->targetDirs[3].'/src/Controller/Homepage.php';

return $this->services['App\Controller\Homepage'] = new \App\Controller\Homepage(${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'});
